VERSION ?= develop

.PHONY: build
build:
	- docker buildx create --name project-v3-builder
	docker buildx use project-v3-builder
	docker buildx build --push --platform=linux/arm64,linux/amd64 --tag jam2in/arcus-memcached:${VERSION} --progress tty .
