name: CI

on:
  push:
      branches: [ "master" ]
  pull_request:
      branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Arcus Server Dependency Packages
      run: sudo apt-get install -qq build-essential autoconf automake libtool
    - name: Cache ARCUS Directory
      id: arcus-cache
      uses: actions/cache@v3.3.2
      with:
        path: ~/arcus
        key: ${{runner.os}}-arcus
    - name: Install Arcus Server Dependency Libraries
      if: steps.arcus-cache.outputs.cache-hit != 'true'
      run: ./deps/install.sh $HOME/arcus
    - name: Build Arcus Server
      run: |
          ./config/autorun.sh
          ./configure --enable-zk-integration --with-zk-reconfig --with-libevent=${HOME}/arcus --with-zookeeper=${HOME}/arcus
          make
    - name: Test ARCUS Server
      run: make test
