name: CI

on:
  push:
      branches: [ "master" ]
  pull_request:
      branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Build Arcus Server Image
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        push: false
        load: true
        tags: arcus-memcached
        target: builder
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Run Arcus Server Test
      run: docker run arcus-memcached make test
